In [1]:
import numpy as np


In [4]:
#Exercicio--crie um método para retornar a media dos elementos de um array.
a=np.array([1,2,3,4,5])
print(np.sum(a))


15


In [5]:
len(a)
print(len(a))

5


In [8]:
resultado_genérico=np.sum(a)/len(a)
#Sendo a como um array qualquer.
print(resultado_genérico)

3.0


In [16]:
#Crie uma função que crie uma matriz de zeros em shape 4x3.
b=np.array([0,0,0])
c=np.array([b,b,b,b])
print(c)

[[0 0 0]
 [0 0 0]
 [0 0 0]
 [0 0 0]]
