In [1]:
import numpy as np
a=np.array([1,2,3])
print(a)

[1 2 3]


In [11]:
#array=matriz
b=np.array([(1,2,3),(2,1,9)])
print(b)

[[1 2 3]
 [2 1 9]]


In [6]:
c=np.zeros((4,3))
print(c)

[[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]


In [8]:
d=np.ones((7,3))
print(d)

[[1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]]


In [9]:
e=np.eye(4)
print(e)

[[1. 0. 0. 0.]
 [0. 1. 0. 0.]
 [0. 0. 1. 0.]
 [0. 0. 0. 1.]]


In [12]:
b.max()
#pega o maior elemento da matriz


9

In [13]:
b.min()
#pega o menor elemento da matriz

1

In [14]:
b.sum()
#faz a soma dos elementos da matriz


18

In [15]:
b.mean()
#média dos elementos da matriz

3.0

In [16]:
b.std()
#desvio padrão

2.7688746209726918

In [17]:
#Get dimensions

b.ndim

2

In [18]:
a.ndim

1

In [20]:
#Get Shape

b.shape

(2, 3)

In [21]:
a.shape

(3,)

In [22]:
#Get Type
a.dtype


dtype('int32')

In [23]:
A=np.array([1,2,3],dtype='int16')
A.dtype

dtype('int16')

In [24]:
##### separando #######


In [27]:
c=np.array([(1,2,3,4,5,6),(7,8,9,10,11,12)])
print(c)

[[ 1  2  3  4  5  6]
 [ 7  8  9 10 11 12]]


In [26]:
c.shape

(2, 6)

In [30]:
c[0,5]

6

In [31]:
c[1,5]

12

In [33]:
#get a specific row
c[0,:]

array([1, 2, 3, 4, 5, 6])

In [34]:
#get a specific column
c[:,0]

array([1, 7])

In [35]:
#Working with index (startindex):(endindex)
c[0,1:5]

array([2, 3, 4, 5])

In [36]:
c[1,5]

12

In [37]:
#Change the element
c[1,5]=31 
print(c)

[[ 1  2  3  4  5  6]
 [ 7  8  9 10 11 31]]


In [11]:
# 3D EXAMPLES



NameError: name 'np' is not defined

In [14]:
import numpy as np
np.full((3,2,3),99)

array([[[99, 99, 99],
        [99, 99, 99]],

       [[99, 99, 99],
        [99, 99, 99]],

       [[99, 99, 99],
        [99, 99, 99]]])

In [18]:
np.random.rand(4)

array([0.63190626, 0.1852532 , 0.07170049, 0.49900232])

In [26]:
np.random.randint(7,20)

12

In [32]:
arr=np.array([[1,2,3]])
r1=np.repeat(arr,3,axis=0)
print(r1)

[[1 2 3]
 [1 2 3]
 [1 2 3]]


In [33]:
#mathematics 


In [36]:
k=np.array([1,2,3,4])
print(k)

[1 2 3 4]


In [37]:
np.sin(k)

array([ 0.84147098,  0.90929743,  0.14112001, -0.7568025 ])